name: Publish Docker
on:
  push:
    branches: [master]
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Package and Version
        id: version
        run: |
          set +e
          _=$(echo "$GITHUB_REF" | grep "^refs/heads/")
          if [ $? -eq 0 ]; then
            # branch
            if [ "$GITHUB_REF" = "refs/heads/master" ]; then
              VER=latest
              PKG=etheno
            else
              VER=testing
              PKG=etheno
            fi
          fi
          _=$(echo "$GITHUB_REF" | grep "^refs/tags/")
          if [ $? -eq 0 ]; then
            # tag
            # refs/tags/v1.X => v1.X
            VER=$(echo "$GITHUB_REF" | sed -e 's/.*\///')
            PKG=etheno
          fi
          set -e
          echo "::set-output name=PKG::$PKG"
          echo "::set-output name=VER::$VER"

      - name: Docker Build
        run: docker build -t ${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }} --load --target final .

      - name: Docker Push
        run: |
          docker tag ${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }} ghcr.io/${{ github.repository }}/${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }}
          docker push ghcr.io/${{ github.repository }}/${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }}

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Docker Push
        run: |
          docker tag ${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }} registry.hub.docker.com/trailofbits/${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }}
          docker push registry.hub.docker.com/trailofbits/${{ steps.version.outputs.PKG }}:${{ steps.version.outputs.VER }}
